baseURL = "https://example.com/"
languageCode = "en-us"
title = "S-CORE"

[menu]

  [[menu.main]]
    identifier = "home"
    name       = "Home"
    url        = "/"
    weight     = 1

  [[menu.main]]
    identifier = "news"
    name       = "News & Events"
    url        = "/news/"
    weight     = 2

  [[menu.main]]
    identifier = "campus"
    name       = "Campus"
    url        = "/training-modules/"
    weight     = 3

  [[menu.main]]
    identifier = "about"
    name       = "About Us"
    url        = "/about-us/"
    weight     = 4

  [[menu.main]]
    identifier = "docs"
    name       = "Docs"
    url        = "/docs/"
    weight     = 5

  [[menu.main]]
    identifier = "contribute"
    name       = "How To Contribute"
    url        = "#"
    weight     = 6
